#!/usr/bin/env python3
import duckduckgo
import sys
import getopt

filters = ["duckduckgo.com"] #filter search engine results

def usage():
	print ('Usage: ddg [options] <keywords>', file=sys.stderr)
	print ('    -n N    return N search results', file=sys.stderr)

def isLinkInHistory(linkHistory, url):
    for element in filters:
        if element in url:
            return True
    if not url in linkHistory:
        linkHistory.append(url)
        return False
    else:
        return True

def main():
	max_results = 0

	try:
		optlist, args = getopt.getopt(sys.argv[1:], 'n:')
	except getopt.GetoptError as err:
		print (str(err), file=sys.stderr)
		sys.exit(2)

	for o, a in optlist:
		if o == '-n':
			max_results = int(a)

	if len(args) < 1:
		usage()
		sys.exit(2)

	keywords = args

	linkHistory = []
	for result in duckduckgo.search(keywords, max_results=max_results):
		#remove unwanted links
		if not isLinkInHistory(linkHistory, result):
			print(result)
	
	

if __name__ == '__main__':
	main()


